# This is an exported workflow. Editing this file is not recommended.

name: Token Tester
trigger:
    next:
        - Loop
    type: On demand
loops:
    Loop:
        display: While Loop Iteration is less than 1000
        name: While Loop Iteration is less than 1000
        for:
            input: ""
            condition: Loop.Iteration:<1000
            condition_display:
                - Loop Iteration is less than 1000
            continue_on_partial_execution: false
            sequential: true
        trigger:
            next:
                - PollHandler2
        actions:
            PollHandler2:
                id: 4cf39421771949adbfaed172d908b64b_44233d104b1e4b5d8cc9a03066e941fa
                name: poll-handler - 2
                properties: {}
                version_constraint: ~0
